### ISSUE TITLE
fixed typos in Users' Manual

### ISSUE THREAD

**Issue by wpdevelopment11** [Spivoxity/obc-3#47]
While reading [Users' Manual](https://spivey.oriel.ox.ac.uk/wiki/images-corner/c/ce/Obcman-3.1.pdf) I noticed some typos. I have attached a patch.

[0001-fix-typos.patch](https://github.com/Spivoxity/obc-3/files/12360096/0001-fix-typos.patch)

**Comment by Spivoxity** [comment]
Thanks, I've corrected these and others in the current source.
